import { asTicketId, asCityId } from '@trm/shared';
import type { TicketDef } from './types';

type Row = [string, string, string, number];

const longRows: readonly Row[] = [
  ['L1', 'penghu', 'taipei', 23],
  ['L2', 'matsu', 'orchidisland', 30],
  ['L3', 'kinmen', 'luodong', 24],
  ['L4', 'zhunan', 'chishang', 22],
  ['L5', 'banqiao', 'tainan', 22],
  ['L6', 'hengchun', 'nantou', 18],
  ['L7', 'jiji', 'keelung', 18],
  ['L8', 'kaohsiung', 'zhunan', 20],
  ['L9', 'pingxi', 'zuoying', 21],
];

const shortRows: readonly Row[] = [
  ['S1', 'matsu', 'keelung', 8],
  ['S2', 'matsu', 'taipei', 10],
  ['S3', 'kinmen', 'shalu', 6],
  ['S4', 'kinmen', 'penghu', 6],
  ['S5', 'kinmen', 'tainan', 9],
  ['S6', 'penghu', 'chiayi', 7],
  ['S7', 'penghu', 'kaohsiung', 4],
  ['S8', 'penghu', 'liuqiu', 6],
  ['S9', 'keelung', 'guishan', 5],
  ['S10', 'taipei', 'luodong', 5],
  ['S11', 'taipei', 'hualien', 9],
  ['S12', 'taipei', 'zhunan', 6],
  ['S13', 'taipei', 'miaoli', 7],
  ['S14', 'taipei', 'taichung', 11],
  ['S15', 'banqiao', 'guishan', 6],
  ['S16', 'banqiao', 'zhunan', 5],
  ['S17', 'banqiao', 'taichung', 10],
  ['S18', 'taoyuan', 'hsinchu', 2],
  ['S19', 'taoyuan', 'hualien', 9],
  ['S20', 'taoyuan', 'shalu', 8],
  ['S21', 'taoyuan', 'miaoli', 5],
  ['S22', 'hsinchu', 'shalu', 6],
  ['S23', 'hsinchu', 'taichung', 7],
  ['S24', 'hsinchu', 'yuli', 11],
  ['S25', 'zhunan', 'shalu', 4],
  ['S26', 'zhunan', 'changhua', 8],
  ['S27', 'zhunan', 'taichung', 6],
  ['S28', 'miaoli', 'jiji', 8],
  ['S29', 'miaoli', 'taichung', 4],
  ['S30', 'miaoli', 'yuli', 8],
  ['S31', 'miaoli', 'douliu', 10],
  ['S32', 'shalu', 'changhua', 4],
  ['S33', 'shalu', 'huwei', 7],
  ['S34', 'taichung', 'hualien', 7],
  ['S35', 'taichung', 'douliu', 4],
  ['S36', 'taichung', 'chiayi', 7],
  ['S37', 'taichung', 'tainan', 11],
  ['S38', 'changhua', 'nantou', 4],
  ['S39', 'changhua', 'jiji', 4],
  ['S40', 'changhua', 'taitung', 12],
  ['S41', 'nantou', 'yuli', 4],
  ['S42', 'nantou', 'taitung', 8],
  ['S43', 'nantou', 'chiayi', 5],
  ['S44', 'jiji', 'greenisland', 9],
  ['S45', 'jiji', 'kaohsiung', 10],
  ['S46', 'douliu', 'pingtung', 11],
  ['S47', 'douliu', 'alishan', 4],
  ['S48', 'douliu', 'tainan', 7],
  ['S49', 'huwei', 'tainan', 6],
  ['S50', 'huwei', 'liuqiu', 10],
  ['S51', 'huwei', 'chiayi', 4],
  ['S52', 'alishan', 'pingtung', 10],
  ['S53', 'alishan', 'tainan', 6],
  ['S54', 'chiayi', 'tainan', 4],
  ['S55', 'chiayi', 'kaohsiung', 6],
  ['S56', 'chiayi', 'hengchun', 10],
  ['S57', 'chiayi', 'taitung', 8],
  ['S58', 'tainan', 'pingtung', 4],
  ['S59', 'tainan', 'chaozhou', 5],
  ['S60', 'tainan', 'greenisland', 9],
  ['S61', 'kaohsiung', 'chishang', 8],
  ['S62', 'kaohsiung', 'orchidisland', 9],
  ['S63', 'pingtung', 'liuqiu', 4],
  ['S64', 'yilan', 'hualien', 6],
  ['S65', 'yilan', 'chishang', 10],
  ['S66', 'luodong', 'guishan', 2],
  ['S67', 'luodong', 'greenisland', 11],
  ['S68', 'luodong', 'yuli', 6],
  ['S69', 'hualien', 'taitung', 6],
  ['S70', 'yuli', 'taitung', 4],
  ['S71', 'yuli', 'orchidisland', 6],
  ['S72', 'chishang', 'orchidisland', 5],
  ['S73', 'taitung', 'orchidisland', 3],
  ['S74', 'taitung', 'chaozhou', 6],
  ['S75', 'taitung', 'hengchun', 8],
];

const toTicket =
  (deck: 'LONG' | 'SHORT') =>
  ([id, a, b, value]: Row): TicketDef => ({
    id: asTicketId(id),
    a: asCityId(a),
    b: asCityId(b),
    value,
    deck,
  });

export const LONG_TICKETS: readonly TicketDef[] = longRows.map(toTicket('LONG'));
export const SHORT_TICKETS: readonly TicketDef[] = shortRows.map(toTicket('SHORT'));
export const TICKETS: readonly TicketDef[] = [...LONG_TICKETS, ...SHORT_TICKETS];
