// The themed chrome kit — every non-game screen builds from these primitives so the whole app
// shares one visual language ("railway timetable on warm paper", tokens from @trm/client-core)
// and follows the light/dark theme automatically. The signature element is the route glyph: the
// brand mark's car-slot atom reused as a divider/ornament, so app chrome quotes the game board.
import type { PropsWithChildren, ReactNode } from 'react';
import {
  Image,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
  type StyleProp,
  type TextInputProps,
  type ViewStyle,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { RADIUS, SPACE, useTheme } from './useTheme';
// The shared rail-ticket mark (same artwork as apps/web/public/icon.svg, generated by
// scripts/gen-brand-assets.js), used at both sizes below — mirrors web's BrandBanner icon.
import BRAND_ICON from '../../assets/icon.png';

/** Full-screen themed background (+ safe-area padding). `scroll` wraps children in a ScrollView. */
export function Screen({
  children,
  scroll = false,
  centered = false,
  style,
}: PropsWithChildren<{ scroll?: boolean; centered?: boolean; style?: StyleProp<ViewStyle> }>) {
  const { tokens } = useTheme();
  const insets = useSafeAreaInsets();
  const pad = {
    paddingTop: insets.top,
    paddingBottom: insets.bottom,
    paddingLeft: insets.left,
    paddingRight: insets.right,
  };
  if (scroll) {
    return (
      <ScrollView
        style={[{ flex: 1, backgroundColor: tokens.paper }, pad]}
        contentContainerStyle={[styles.scrollContent, centered && styles.centeredContent, style]}
        keyboardShouldPersistTaps="handled"
      >
        {children}
      </ScrollView>
    );
  }
  return (
    <View
      style={[
        { flex: 1, backgroundColor: tokens.paper },
        pad,
        centered && styles.centeredContent,
        style,
      ]}
    >
      {children}
    </View>
  );
}

/** The fixed bilingual logotype (mark + stacked wordmark) — ports web's BrandBanner lockup 1:1
 *  (`.brand-banner` in apps/web app.css): the −6° skew, em-derived tracking, and the fixed ember
 *  orange that never switches with theme or locale. */
export function BrandWordmark({ size = 'header' }: { size?: 'header' | 'hero' }) {
  const { tokens } = useTheme();
  const hero = size === 'hero';
  const iconSize = hero ? 80 : 36;
  const zhSize = hero ? 48 : 17;
  const enSize = hero ? 16 : 7;
  return (
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: hero ? SPACE[3] : SPACE[2] }}>
      <Image
        source={BRAND_ICON}
        style={{ width: iconSize, height: iconSize, borderRadius: iconSize * 0.22 }}
      />
      <View style={{ gap: 3 }}>
        <Text
          style={{
            // Web hardcodes this hex too — the 台鐵任務 line stays this ember in both themes.
            color: '#e55509',
            fontWeight: '700',
            fontSize: zhSize,
            lineHeight: zhSize,
            letterSpacing: zhSize * 0.056,
            transform: [{ skewX: '-6deg' }],
          }}
        >
          台鐵任務
        </Text>
        <Text
          style={{
            color: tokens.brandNavy,
            fontWeight: '600',
            fontSize: enSize,
            letterSpacing: enSize * 0.455,
            transform: [{ skewX: '-6deg' }],
          }}
        >
          TRMISSION
        </Text>
      </View>
    </View>
  );
}

/** The brand mark's atom as chrome ornament: hub — car slots — hub. Reads as a route, works as
 *  a divider. Pass a colour to override the default EMU blue (e.g. inkSoft for quiet contexts). */
export function RouteGlyph({ color, slots = 3 }: { color?: string; slots?: number }) {
  const { tokens } = useTheme();
  const c = color ?? tokens.blue;
  return (
    <View style={styles.glyphRow} accessibilityElementsHidden importantForAccessibility="no">
      <View style={[styles.glyphHub, { borderColor: tokens.brandNavy }]}>
        <View style={[styles.glyphHubCore, { backgroundColor: c }]} />
      </View>
      {Array.from({ length: slots }, (_, i) => (
        <View key={i} style={[styles.glyphSlot, { backgroundColor: c }]} />
      ))}
      <View style={[styles.glyphHub, { borderColor: tokens.brandNavy }]}>
        <View style={[styles.glyphHubCore, { backgroundColor: c }]} />
      </View>
    </View>
  );
}

/** Surface card: the timetable sheet everything sits on. */
export function Card({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) {
  const { tokens } = useTheme();
  return (
    <View
      style={[
        styles.card,
        { backgroundColor: tokens.surface, borderColor: tokens.line, shadowColor: tokens.ink },
        style,
      ]}
    >
      {children}
    </View>
  );
}

interface DepartureRowProps {
  /** A string renders in the row's title voice; pass a node for custom lockups (e.g. a code chip). */
  title: ReactNode;
  /** Leading glyph, rendered in a rounded badge (mirrors web's welcome-option-icon). */
  icon?: ReactNode;
  desc?: string;
  /** Inline slot right of the title (status tick, badge). */
  meta?: ReactNode;
  /** Bottom boarding line ("開始教學 ›") — welcome tickets use this instead of a button. */
  cta?: string;
  /** Right-edge slot; a pressable row without a cta gets a chevron by default. */
  trailing?: ReactNode;
  /** Train-line stripe on the left edge: 'accent' marks the recommended departure. */
  stripe?: 'accent' | 'quiet';
  onPress?(): void;
  disabled?: boolean;
  testID?: string;
  style?: StyleProp<ViewStyle>;
}

/** Departure card: the timetable's pressable unit — a hairline ticket with an optional
 *  train-line stripe on the left edge, title/desc column, and a boarding chevron. Home and
 *  the welcome takeover list everything boardable (tutorial, offline games, rooms) through it. */
export function DepartureRow({
  title,
  icon,
  desc,
  meta,
  cta,
  trailing,
  stripe,
  onPress,
  disabled,
  testID,
  style,
}: DepartureRowProps) {
  const { tokens } = useTheme();
  const accent = stripe === 'accent';
  const right =
    trailing ??
    (onPress && cta == null ? (
      <Text style={[styles.depChevron, { color: tokens.inkSoft }]}>›</Text>
    ) : null);
  const body = (
    <>
      {stripe && (
        <View
          style={[styles.depStripe, { backgroundColor: accent ? tokens.accent : tokens.line }]}
        />
      )}
      {icon != null && (
        <View style={[styles.depIcon, { backgroundColor: tokens.surface2 }]}>{icon}</View>
      )}
      <View style={styles.depBody}>
        <View style={styles.depTitleRow}>
          {typeof title === 'string' ? (
            <Text style={[styles.depTitle, { color: tokens.ink }]}>{title}</Text>
          ) : (
            title
          )}
          {meta}
        </View>
        {desc != null && <Text style={[styles.depDesc, { color: tokens.inkSoft }]}>{desc}</Text>}
        {cta != null && (
          <Text style={[styles.depCta, { color: accent ? tokens.accent : tokens.ink }]}>
            {cta} ›
          </Text>
        )}
      </View>
      {right != null && <View style={styles.depTrailing}>{right}</View>}
    </>
  );
  const surface = {
    backgroundColor: tokens.surface,
    borderColor: tokens.line,
  };
  if (!onPress) {
    return <View style={[styles.depRow, surface, style]}>{body}</View>;
  }
  return (
    <Pressable
      accessibilityRole="button"
      testID={testID}
      disabled={disabled}
      onPress={onPress}
      style={({ pressed }) => [
        styles.depRow,
        surface,
        pressed && styles.pressed,
        disabled && styles.disabled,
        style,
      ]}
    >
      {body}
    </Pressable>
  );
}

interface ButtonProps {
  title: string;
  onPress(): void;
  disabled?: boolean;
  testID?: string;
  /** Optional leading glyph (SecondaryButton only) — e.g. an OAuth provider mark. */
  icon?: ReactNode;
}

export function PrimaryButton({ title, onPress, disabled, testID }: ButtonProps) {
  const { tokens } = useTheme();
  return (
    <Pressable
      accessibilityRole="button"
      testID={testID}
      disabled={disabled}
      onPress={onPress}
      style={({ pressed }) => [
        styles.button,
        { backgroundColor: tokens.blue },
        pressed && styles.pressed,
        disabled && styles.disabled,
      ]}
    >
      <Text style={styles.primaryButtonText}>{title}</Text>
    </Pressable>
  );
}

export function SecondaryButton({ title, onPress, disabled, testID, icon }: ButtonProps) {
  const { tokens } = useTheme();
  return (
    <Pressable
      accessibilityRole="button"
      testID={testID}
      disabled={disabled}
      onPress={onPress}
      style={({ pressed }) => [
        styles.button,
        styles.secondaryButton,
        { backgroundColor: tokens.surface, borderColor: tokens.line },
        pressed && styles.pressed,
        disabled && styles.disabled,
      ]}
    >
      <View style={styles.secondaryButtonContent}>
        {icon}
        <Text style={[styles.secondaryButtonText, { color: tokens.ink }]}>{title}</Text>
      </View>
    </Pressable>
  );
}

export function LinkButton({ title, onPress, disabled, testID }: ButtonProps) {
  const { tokens } = useTheme();
  return (
    <Pressable accessibilityRole="button" testID={testID} disabled={disabled} onPress={onPress}>
      <Text style={[styles.link, { color: tokens.blue }, disabled && styles.disabled]}>
        {title}
      </Text>
    </Pressable>
  );
}

/** Themed text input. */
export function Field(props: TextInputProps) {
  const { tokens } = useTheme();
  return (
    <TextInput
      placeholderTextColor={tokens.inkSoft}
      {...props}
      style={[
        styles.field,
        {
          backgroundColor: tokens.surface,
          borderColor: tokens.line,
          color: tokens.ink,
        },
        props.style,
      ]}
    />
  );
}

/** Small-caps section label (timetable column header voice). */
export function SectionLabel({ children }: PropsWithChildren) {
  const { tokens } = useTheme();
  return <Text style={[styles.sectionLabel, { color: tokens.inkSoft }]}>{children}</Text>;
}

export function MutedText({ children, center }: PropsWithChildren<{ center?: boolean }>) {
  const { tokens } = useTheme();
  return (
    <Text style={[{ color: tokens.inkSoft, fontSize: 14 }, center && { textAlign: 'center' }]}>
      {children}
    </Text>
  );
}

export function ErrorText({ children }: PropsWithChildren) {
  const { tokens } = useTheme();
  return <Text style={{ color: tokens.danger, textAlign: 'center' }}>{children}</Text>;
}

const styles = StyleSheet.create({
  scrollContent: { flexGrow: 1, padding: SPACE[6] },
  centeredContent: { justifyContent: 'center' },
  card: {
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    padding: SPACE[4],
    gap: SPACE[3],
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  depRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderWidth: 1,
    borderRadius: RADIUS.md,
    overflow: 'hidden',
  },
  depStripe: { width: 4 },
  depIcon: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginLeft: 14,
  },
  depBody: { flex: 1, padding: 14, gap: 5 },
  depTitleRow: { flexDirection: 'row', alignItems: 'center', gap: SPACE[2] },
  depTitle: { fontSize: 16, fontWeight: '700', flexShrink: 1 },
  depDesc: { fontSize: 14, lineHeight: 20 },
  depCta: { fontSize: 15, fontWeight: '700', marginTop: 3 },
  depChevron: { fontSize: 22, fontWeight: '400', lineHeight: 24 },
  depTrailing: { justifyContent: 'center', paddingRight: 14 },
  glyphRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  glyphHub: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 3.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  glyphHubCore: { width: 5, height: 5, borderRadius: 2.5 },
  glyphSlot: { width: 22, height: 11, borderRadius: 3 },
  button: {
    borderRadius: RADIUS.md,
    paddingVertical: 14,
    paddingHorizontal: SPACE[4],
    alignItems: 'center',
  },
  secondaryButton: { borderWidth: 1 },
  secondaryButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  secondaryButtonText: { fontSize: 16, fontWeight: '500' },
  link: { textAlign: 'center', paddingVertical: 6, fontWeight: '500' },
  field: { borderWidth: 1, borderRadius: RADIUS.md, padding: 12, fontSize: 16 },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  pressed: { opacity: 0.85 },
  disabled: { opacity: 0.5 },
});
