// Injects the Live Activity widget-extension target into the Xcode project (issue #43).
//
// `apps/mobile/ios` is Continuous Native Generation — regenerated by `expo prebuild`, never
// committed — so the extension target cannot live in a checked-in .xcodeproj: it has to be created
// on every prebuild. This plugin does exactly that, using the `xcode` pbxproj library that
// @expo/config-plugins already ships (no new dependency, no EAS).
//
// It also COPIES `modules/live-activity/ios/TRMissionActivityAttributes.swift` into the widget
// folder. That file is the ActivityKit contract and must compile into BOTH the app (where the local
// Expo module starts/updates the activity) and the extension (where it is rendered); copying from
// one source on every prebuild is what makes drift impossible — ActivityKit matches an activity to
// its widget by that type, and a mismatch renders a blank card with no error anywhere.
//
// Plain CommonJS on purpose: Expo resolves `plugins: ['./plugins/withLiveActivity']` with a bare
// `require`, so nothing here goes through a TS transform.
const { withXcodeProject } = require('@expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/** Xcode target + folder name for the extension. */
const TARGET_NAME = 'TRMissionWidget';
/** Appended to the app's bundle id — the widget needs its own App ID + provisioning profile
 *  (fastlane/Matchfile lists it; the beta lane signs both targets). */
const BUNDLE_SUFFIX = 'LiveActivity';
/** ActivityKit is iOS 16.1+; SDK 56's own floor is 16.4, so this is only a backstop. */
const MIN_DEPLOYMENT_TARGET = '16.4';

/** Widget-only sources (checked in under apps/mobile/ios-live-activity). */
const WIDGET_SOURCES = ['TRMissionWidgetBundle.swift', 'TRMissionLiveActivityWidget.swift'];
/** The shared contract, copied out of the local Expo module so both targets compile one file. */
const SHARED_SOURCE = 'TRMissionActivityAttributes.swift';
const INFO_PLIST = `${TARGET_NAME}-Info.plist`;

/** Strip the pbxproj's quoting so a name/setting can be compared as a plain string. */
const unquote = (value) => String(value ?? '').replace(/^"(.*)"$/, '$1');

/**
 * Find a native target by name, tolerating pbxproj quoting.
 *
 * `xcode`'s own `pbxTargetByName` matches a target's section COMMENT verbatim — and `addTarget`
 * writes that comment quoted (`"TRMissionWidget"`) while Xcode's template writes the app's bare
 * (`TRMission`). So the library helper can never find a target this plugin created, which silently
 * defeated the idempotency guard below: a non-clean `expo prebuild` added a SECOND widget target.
 */
function nativeTargetByName(project, name) {
  const section = project.pbxNativeTargetSection() ?? {};
  for (const key of Object.keys(section)) {
    if (key.endsWith('_comment')) continue;
    const target = section[key];
    if (target && typeof target === 'object' && unquote(target.name) === name) return target;
  }
  return null;
}

/**
 * Delete every key whose value is `undefined` from the objects this plugin created.
 *
 * The pbxproj writer's `omitEmptyValues` defaults to FALSE, so a key that exists but is undefined is
 * serialized as the literal string `undefined`. That is not cosmetic: `path = undefined` on the
 * widget's group made Xcode resolve its sources to `ios/undefined/TRMissionWidget/…` and fail the
 * archive with "Build input files cannot be found" — while the in-memory project still looked
 * perfect, which is why the plugin's own test now asserts on the SERIALIZED output.
 *
 * A sweep over every section is safe: entries parsed from an existing project only ever hold
 * strings/arrays/objects, so this can only touch what the `xcode` helpers just added.
 */
function dropUndefinedValues(project) {
  for (const section of Object.values(project.hash.project.objects)) {
    if (!section || typeof section !== 'object') continue;
    for (const entry of Object.values(section)) {
      if (!entry || typeof entry !== 'object') continue;
      for (const key of Object.keys(entry)) {
        if (entry[key] === undefined) delete entry[key];
      }
    }
  }
}

/**
 * Every XCBuildConfiguration belonging to one target, found through the target's own
 * buildConfigurationList — matching on PRODUCT_NAME would also catch the app's configs whenever a
 * future rename made the two names collide.
 */
function configurationsForTarget(project, nativeTarget) {
  const lists = project.hash.project.objects.XCConfigurationList ?? {};
  const configs = project.pbxXCBuildConfigurationSection();
  const list = lists[nativeTarget?.buildConfigurationList];
  if (!list) return [];
  return (list.buildConfigurations ?? [])
    .map((ref) => configs[ref.value])
    .filter((c) => c && typeof c === 'object' && c.buildSettings);
}

/** The app target's own build settings (source for the deployment target + team id). */
function appBuildSettings(project, appTargetName) {
  const configs = configurationsForTarget(project, nativeTargetByName(project, appTargetName));
  // Release first: it is what gym archives.
  const release = configs.find((c) => unquote(c.name) === 'Release');
  return (release ?? configs[0])?.buildSettings ?? {};
}

function copyWidgetSources(projectRoot, widgetDir) {
  fs.mkdirSync(widgetDir, { recursive: true });

  const widgetSrcDir = path.join(projectRoot, 'ios-live-activity');
  for (const name of WIDGET_SOURCES) {
    fs.copyFileSync(path.join(widgetSrcDir, name), path.join(widgetDir, name));
  }
  fs.copyFileSync(path.join(widgetSrcDir, 'Info.plist'), path.join(widgetDir, INFO_PLIST));

  const sharedSrc = path.join(
    projectRoot,
    'modules',
    'live-activity',
    'ios',
    SHARED_SOURCE,
  );
  if (!fs.existsSync(sharedSrc)) {
    throw new Error(
      `withLiveActivity: ${sharedSrc} is missing — it is the shared ActivityKit contract and must compile into both the app and the widget.`,
    );
  }
  fs.copyFileSync(sharedSrc, path.join(widgetDir, SHARED_SOURCE));
}

/**
 * The whole mutation, split out from the plugin wrapper so it can be exercised against a real
 * template pbxproj in a unit test (`withLiveActivity.test.ts`) — no Mac, no prebuild. Returns false
 * when the target already exists (a non-clean prebuild re-runs the mods over an existing project).
 *
 * @param {import('xcode').XcodeProject} project parsed pbxproj (the `withXcodeProject` modResults)
 * @param {{appName: string, appBundleId: string, projectRoot: string, iosRoot: string,
 *          buildNumber: string, marketingVersion: string}} opts
 */
function applyLiveActivityTarget(project, opts) {
  const { appName, appBundleId, projectRoot, iosRoot, buildNumber, marketingVersion } = opts;
  if (nativeTargetByName(project, TARGET_NAME)) return false;

  // `addTarget` embeds the extension into — and adds the target dependency to — whatever
  // `getFirstTarget()` returns, so that had better be the app. Fail loudly rather than shipping an
  // .ipa whose extension is silently missing.
  const firstTargetName = unquote(project.getFirstTarget()?.firstTarget?.name);
  if (firstTargetName !== appName) {
    throw new Error(
      `withLiveActivity: expected the first Xcode target to be the app ("${appName}") but found "${firstTargetName}" — prebuild's project layout changed; the widget would be embedded into the wrong target.`,
    );
  }

  copyWidgetSources(projectRoot, path.join(iosRoot, TARGET_NAME));

  // `xcode`'s addTargetDependency silently does NOTHING when the project has no
  // PBXTargetDependency / PBXContainerItemProxy section yet (it guards on both being present) — and
  // Expo's template has neither, shipping a single target with no dependencies. Without the
  // dependency, xcodebuild is free to run the app's embed phase before the extension has been built.
  // Create the empty sections first so the library's own code path applies.
  const objects = project.hash.project.objects;
  objects.PBXTargetDependency = objects.PBXTargetDependency ?? {};
  objects.PBXContainerItemProxy = objects.PBXContainerItemProxy ?? {};

  // Creates the PBXNativeTarget (product type app-extension), its .appex product, the
  // "Embed Foundation Extensions" copy phase on the app target, and the target dependency.
  const target = project.addTarget(
    TARGET_NAME,
    'app_extension',
    TARGET_NAME,
    `${appBundleId}.${BUNDLE_SUFFIX}`,
  );

  const relative = (name) => `${TARGET_NAME}/${name}`;
  const sourceFiles = [...WIDGET_SOURCES, SHARED_SOURCE].map(relative);

  // Sources first: it creates the PBXFileReference + PBXBuildFile entries. `addPbxGroup` below
  // then REUSES those references (it matches on path), so the navigator group and the compile
  // phase point at the same refs instead of duplicating them.
  project.addBuildPhase(sourceFiles, 'PBXSourcesBuildPhase', 'Sources', target.uuid);
  // Shaped like Xcode's own widget template. Empty on purpose: Swift auto-links the frameworks it
  // imports (WidgetKit / SwiftUI / ActivityKit), and the widget bundles no resources — the
  // rendered content all arrives through the activity's ContentState.
  project.addBuildPhase([], 'PBXFrameworksBuildPhase', 'Frameworks', target.uuid);
  project.addBuildPhase([], 'PBXResourcesBuildPhase', 'Resources', target.uuid);

  // A named group with NO path: its children already carry paths relative to the project root
  // (`TRMissionWidget/…`), and giving the group a path too would resolve them one level deeper.
  // `undefined` here is not the same as absent — see dropUndefinedValues, called at the end.
  const group = project.addPbxGroup([...sourceFiles, relative(INFO_PLIST)], TARGET_NAME, undefined);
  // Hang it off the project's own mainGroup (read from PBXProject rather than guessed by shape).
  const mainGroupKey = project.getFirstProject()?.firstProject?.mainGroup;
  if (!mainGroupKey) {
    throw new Error("withLiveActivity: the project has no mainGroup — can't place the widget group.");
  }
  project.addToPbxGroup(group.uuid, mainGroupKey);

  const appSettings = appBuildSettings(project, appName);
  const deploymentTarget = unquote(appSettings.IPHONEOS_DEPLOYMENT_TARGET) || MIN_DEPLOYMENT_TARGET;
  const teamId = unquote(appSettings.DEVELOPMENT_TEAM) || process.env.APPLE_TEAM_ID || '';

  // `addTarget` returns `{uuid, pbxNativeTarget}` — the configuration list hangs off the inner
  // object, not the wrapper.
  for (const configuration of configurationsForTarget(project, target.pbxNativeTarget)) {
    Object.assign(configuration.buildSettings, {
      CLANG_ENABLE_MODULES: 'YES',
      CURRENT_PROJECT_VERSION: `"${buildNumber}"`,
      GENERATE_INFOPLIST_FILE: 'NO',
      INFOPLIST_FILE: `"${relative(INFO_PLIST)}"`,
      IPHONEOS_DEPLOYMENT_TARGET: deploymentTarget,
      MARKETING_VERSION: `"${marketingVersion}"`,
      PRODUCT_BUNDLE_IDENTIFIER: `"${appBundleId}.${BUNDLE_SUFFIX}"`,
      PRODUCT_NAME: `"${TARGET_NAME}"`,
      SKIP_INSTALL: 'YES',
      SWIFT_EMIT_LOC_STRINGS: 'YES',
      SWIFT_VERSION: '5.0',
      TARGETED_DEVICE_FAMILY: '"1,2"',
      // prebuild emits an Automatic/no-team project; fastlane's beta lane flips BOTH targets to
      // manual signing with the match profiles right before gym (see fastlane/Fastfile).
      CODE_SIGN_STYLE: 'Automatic',
      ...(teamId ? { DEVELOPMENT_TEAM: teamId } : {}),
      // Pin the compiler/linker back to the toolchain default for THIS target.
      //
      // `react_native_post_install`'s ccache wiring (USE_CCACHE=1 on the pod install step in
      // mobile-ios.yml) writes CC/LD/CXX/LDPLUSPLUS as `$(REACT_NATIVE_PATH)/scripts/xcode/
      // ccache-clang.sh` onto the PROJECT-level build configurations, which every target inherits —
      // but REACT_NATIVE_PATH/PODS_ROOT are defined only in the Pods xcconfigs, and this extension
      // is not a CocoaPods target. It therefore inherited a path that expands to
      // `/../../../../node_modules/react-native/scripts/xcode/ccache-clang.sh` and failed the
      // archive with "unable to spawn process". A target-level value wins over the project-level
      // one, and RN only ever touches the project level, so this survives `pod install`.
      CC: '$(DT_TOOLCHAIN_DIR)/usr/bin/clang',
      LD: '$(DT_TOOLCHAIN_DIR)/usr/bin/clang',
      CXX: '$(DT_TOOLCHAIN_DIR)/usr/bin/clang++',
      LDPLUSPLUS: '$(DT_TOOLCHAIN_DIR)/usr/bin/clang++',
    });
  }

  // Last, over everything the `xcode` helpers just added: an undefined value would otherwise reach
  // the file as the literal `undefined`.
  dropUndefinedValues(project);

  return true;
}

const withLiveActivity = (config) =>
  withXcodeProject(config, (cfg) => {
    const appBundleId = cfg.ios?.bundleIdentifier;
    if (!appBundleId) {
      throw new Error('withLiveActivity: ios.bundleIdentifier must be set before this plugin runs.');
    }
    applyLiveActivityTarget(cfg.modResults, {
      appName: cfg.modRequest.projectName,
      appBundleId,
      projectRoot: cfg.modRequest.projectRoot,
      iosRoot: cfg.modRequest.platformProjectRoot,
      // The extension's CFBundleVersion/ShortVersionString MUST match the app's or App Store Connect
      // rejects the upload; both come from the same resolved config the app's Info.plist is written
      // from (BUILD_NUMBER/APP_VERSION in app.config.ts).
      buildNumber: String(cfg.ios?.buildNumber ?? '1'),
      marketingVersion: String(cfg.version ?? '1.0.0'),
    });
    return cfg;
  });

module.exports = withLiveActivity;
// Named exports for the unit test (the default export stays the plugin function Expo requires).
module.exports.applyLiveActivityTarget = applyLiveActivityTarget;
module.exports.TARGET_NAME = TARGET_NAME;
module.exports.BUNDLE_SUFFIX = BUNDLE_SUFFIX;
