// Stops a NULL APNs registration error from killing the app (Sentry TRMISSION-MOBILE-4).
//
// UIKit declares the `error` of `application(_:didFailToRegisterForRemoteNotificationsWithError:)`
// nonnull, so Swift imports it as a plain `Error` and every delegate in the chain trusts that.
// iOS 26/27 passes nil anyway: the null arrives as a null `any Error` existential, and the first
// code to bridge it back to NSError — ExpoAppDelegateSubscriberManager, fanning the callback out to
// its @objc subscribers — segfaults in `_swift_stdlib_bridgeErrorToNSError` before expo-notifications
// (a subscriber) ever hears about the failure. EXC_BAD_ACCESS at 0x18 on the main thread, and the
// wedged state survives every retry until the DEVICE is rebooted, so the app is simply unusable for
// as long as it lasts. Neither `expo` nor `expo-modules-core` guards it as of the newest SDK 56
// patch releases (56.0.17 / 56.0.22).
//
// The guard has to sit BELOW that bridge: Swift can't so much as look at a null existential without
// tripping the same crash, but in the ObjC runtime a nil error is just nil. So swap the crashing
// implementation for one typed `NSError?` that substitutes a real error — the failure then stays a
// failure (expo-notifications rejects the pending `getDevicePushTokenAsync()`, see
// `src/push/register.ts`) instead of taking the process down.
//
// `apps/mobile/ios` is CNG, so this is injected into the generated AppDelegate on every prebuild.
// Both anchors below throw when the template moves, which fails `expo prebuild` loudly rather than
// shipping a build that silently lost the guard.
//
// Plain CommonJS on purpose: Expo resolves `plugins: ['./plugins/withRemoteNotificationErrorGuard']`
// with a bare `require`, so nothing here goes through a TS transform.
const { withAppDelegate } = require('@expo/config-plugins');

/** Idempotency marker, and what to grep for in a generated `ios/TRMission/AppDelegate.swift`. */
const MARKER = 'TRM null-APNs-error guard';

/** The class `expo prebuild` writes (SDK 56 bare template), tolerating an access modifier. */
const CLASS_ANCHOR = /^((?:(?:public|open|final)\s+)*class AppDelegate: ExpoAppDelegate \{)$/m;

/** The last import of the template's header block — the ObjC runtime import goes after it. */
const IMPORT_ANCHOR =
  /^(?:(?:public|package|internal|fileprivate|private)\s+)?import [A-Za-z_][\w.]*$/gm;

/** `class_getInstanceMethod` & co. live here; the template imports neither Foundation nor UIKit. */
const RUNTIME_IMPORT = 'import ObjectiveC';

/**
 * Insert the guard into the contents of a generated `AppDelegate.swift`.
 *
 * The override hooks `willFinishLaunchingWithOptions` (which the template leaves alone, unlike
 * `didFinishLaunchingWithOptions`) purely for a place to touch the static — an `init()` override
 * would be rejected, since `ExpoAppDelegate.init()` is `public` rather than `open` and the app is a
 * different module. Registration can only ever be requested from JS, so installing the guard at
 * launch is early enough by a mile.
 *
 * @param {string} contents  the generated AppDelegate.swift
 * @param {{ errorDomain: string }} options  domain for the substituted NSError
 * @returns {string} the patched contents (unchanged if the guard is already there)
 */
function applyRemoteNotificationErrorGuard(contents, { errorDomain }) {
  if (contents.includes(MARKER)) return contents;

  const guard = `
  // ${MARKER} (Sentry TRMISSION-MOBILE-4) — injected by
  // apps/mobile/plugins/withRemoteNotificationErrorGuard.js on every prebuild. Edit it THERE:
  // ios/ is regenerated by \`expo prebuild\` and anything hand-written here is gone.
  //
  // iOS can report a remote-notification registration failure with a nil error even though UIKit
  // declares that parameter nonnull. Swift believes the nonnull import, so the null reaches
  // ExpoAppDelegateSubscriberManager as a null \`any Error\` existential and the process dies in
  // _swift_stdlib_bridgeErrorToNSError the instant the manager bridges it back to NSError for its
  // @objc subscribers — expo-notifications included, so nothing ever rejects the push-token
  // promise. Below the bridge, in the ObjC runtime, nil is representable: swap the implementation
  // for one that takes an \`NSError?\` and substitutes a real error, and the failure stays an
  // ordinary rejected promise.
  public override func application(
    _ application: UIApplication,
    willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {
    _ = AppDelegate.remoteNotificationErrorGuard
    return super.application(application, willFinishLaunchingWithOptions: launchOptions)
  }

  /// Installed once, at launch — long before any JS can call \`registerForRemoteNotifications()\`.
  /// A Swift static is lazy and initialized exactly once, so touching it above is the whole trigger.
  private static let remoteNotificationErrorGuard: Void = {
    let selector = NSSelectorFromString("application:didFailToRegisterForRemoteNotificationsWithError:")
    guard let method = class_getInstanceMethod(AppDelegate.self, selector) else {
      return
    }
    typealias RegistrationFailure = @convention(c) (AnyObject, Selector, UIApplication, NSError?) -> Void
    let unguarded = unsafeBitCast(method_getImplementation(method), to: RegistrationFailure.self)
    let guarded: @convention(block) (AnyObject, UIApplication, NSError?) -> Void = { target, application, error in
      unguarded(target, selector, application, error ?? NSError(
        domain: "${errorDomain}",
        code: -1,
        userInfo: [
          NSLocalizedDescriptionKey: "Remote notification registration failed and the system reported no error."
        ]
      ))
    }
    method_setImplementation(method, imp_implementationWithBlock(guarded))
  }()
`;

  if (!CLASS_ANCHOR.test(contents)) {
    throw new Error(
      "withRemoteNotificationErrorGuard: couldn't find `class AppDelegate: ExpoAppDelegate {` in the generated AppDelegate.swift — the Expo template must have changed.",
    );
  }
  let patched = contents.replace(CLASS_ANCHOR, `$1\n${guard}`);

  if (!patched.includes(RUNTIME_IMPORT)) {
    const imports = [...patched.matchAll(IMPORT_ANCHOR)];
    const last = imports[imports.length - 1];
    if (!last) {
      throw new Error(
        'withRemoteNotificationErrorGuard: the generated AppDelegate.swift has no import block to add `import ObjectiveC` after.',
      );
    }
    const end = last.index + last[0].length;
    patched = `${patched.slice(0, end)}\n${RUNTIME_IMPORT}${patched.slice(end)}`;
  }

  return patched;
}

const withRemoteNotificationErrorGuard = (config) =>
  withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error(
        `withRemoteNotificationErrorGuard: expected a Swift AppDelegate, got ${cfg.modResults.language}.`,
      );
    }
    cfg.modResults.contents = applyRemoteNotificationErrorGuard(cfg.modResults.contents, {
      // Reverse-DNS domain for the substituted error, from the one bundle id in app.config.ts.
      errorDomain: `${cfg.ios?.bundleIdentifier ?? 'app'}.remote-notifications`,
    });
    return cfg;
  });

module.exports = withRemoteNotificationErrorGuard;
// Named exports for the unit test (the default export stays the plugin function Expo requires).
module.exports.applyRemoteNotificationErrorGuard = applyRemoteNotificationErrorGuard;
module.exports.MARKER = MARKER;
