import { asRouteId, asCityId } from '@trm/shared';
import type { RouteDef } from '../types';

const r = asRouteId;
const c = asCityId;

/**
 * 91 routes, the draft's own network verbatim (only ids renumbered on adoption). Unlike the two
 * TRMission-authored maps this one uses the full custom-map vocabulary in combination:
 *  - **Broken rail (斷軌)** on all four Yangmingshan approaches — the mountain roads must be
 *    repaired before they can be claimed.
 *  - **River ferries**: the gray `ferryLocos` crossings inside the basin (新莊–板橋, 中和–大坪林,
 *    鶯歌–三峽) are the Tamsui-system river crossings, besides the true estuary/sea ferries
 *    (淡水/漁人碼頭–八里, 基隆/八斗子–基隆嶼 — the islet pair being a double ferry).
 *  - **Tunnels** are the 雪山山脈 and 平溪 crossings — 礁溪–石碇 (8) and 烏來–礁溪 (6) bore the
 *    very wall the relief layer draws.
 * Every `bow` is the author's hand-tuned curve.
 */
export const TAIPEI_TRANSIT_ROUTES: readonly RouteDef[] = [
  {
    id: r('TTR1'),
    a: c('tt_shilin'),
    b: c('tt_taipei'),
    color: 'RED',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.1,
  },
  {
    id: r('TTR2'),
    a: c('tt_beitou'),
    b: c('tt_shilin'),
    color: 'WHITE',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.6,
  },
  {
    id: r('TTR3'),
    a: c('tt_tamsui'),
    b: c('tt_beitou'),
    color: 'RED',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: 1.7,
  },
  {
    id: r('TTR4'),
    a: c('tt_taipei'),
    b: c('tt_cksmemorial'),
    color: 'BLACK',
    length: 1,
    doubleGroup: 'A',
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR5'),
    a: c('tt_taipei'),
    b: c('tt_cksmemorial'),
    color: 'GREEN',
    length: 1,
    doubleGroup: 'A',
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR6'),
    a: c('tt_daan'),
    b: c('tt_cksmemorial'),
    color: 'RED',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR7'),
    a: c('tt_nangang'),
    b: c('tt_neihu'),
    color: 'GREEN',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: 0.5,
  },
  {
    id: r('TTR8'),
    a: c('tt_neihu'),
    b: c('tt_shilin'),
    color: 'YELLOW',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: 0.7,
  },
  {
    id: r('TTR9'),
    a: c('tt_daan'),
    b: c('tt_muzha'),
    color: 'WHITE',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.1,
  },
  {
    id: r('TTR10'),
    a: c('tt_sanchong'),
    b: c('tt_xinzhuang'),
    color: 'BLUE',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
    bow: 0.1,
  },
  {
    id: r('TTR11'),
    a: c('tt_sanchong'),
    b: c('tt_taipei'),
    color: 'PURPLE',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.5,
  },
  {
    id: r('TTR12'),
    a: c('tt_banqiao'),
    b: c('tt_taipei'),
    color: 'GRAY',
    length: 2,
    doubleGroup: 'C',
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.7,
  },
  {
    id: r('TTR13'),
    a: c('tt_banqiao'),
    b: c('tt_taipei'),
    color: 'BLUE',
    length: 2,
    doubleGroup: 'C',
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.7,
  },
  {
    id: r('TTR14'),
    a: c('tt_nangang'),
    b: c('tt_qidu'),
    color: 'GRAY',
    length: 2,
    doubleGroup: 'F',
    ferryLocos: 0,
    isTunnel: false,
    bow: 0,
  },
  {
    id: r('TTR15'),
    a: c('tt_nangang'),
    b: c('tt_qidu'),
    color: 'ORANGE',
    length: 2,
    doubleGroup: 'F',
    ferryLocos: 0,
    isTunnel: false,
    bow: 0,
  },
  {
    id: r('TTR16'),
    a: c('tt_qidu'),
    b: c('tt_ruifang'),
    color: 'GRAY',
    length: 4,
    doubleGroup: 'H',
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.6,
  },
  {
    id: r('TTR17'),
    a: c('tt_qidu'),
    b: c('tt_ruifang'),
    color: 'PURPLE',
    length: 4,
    doubleGroup: 'H',
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.6,
  },
  {
    id: r('TTR18'),
    a: c('tt_xinzhuang'),
    b: c('tt_banqiao'),
    color: 'GRAY',
    length: 2,
    ferryLocos: 2,
    isTunnel: false,
    bow: -0.1,
  },
  {
    id: r('TTR19'),
    a: c('tt_banqiao'),
    b: c('tt_zhonghe'),
    color: 'YELLOW',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: 0.2,
  },
  {
    id: r('TTR20'),
    a: c('tt_zhonghe'),
    b: c('tt_dapinglin'),
    color: 'GRAY',
    length: 2,
    ferryLocos: 2,
    isTunnel: false,
    bow: 0.3,
  },
  {
    id: r('TTR21'),
    a: c('tt_dapinglin'),
    b: c('tt_muzha'),
    color: 'YELLOW',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: 1.6,
  },
  {
    id: r('TTR22'),
    a: c('tt_cksmemorial'),
    b: c('tt_dapinglin'),
    color: 'PURPLE',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.7,
  },
  {
    id: r('TTR23'),
    a: c('tt_dapinglin'),
    b: c('tt_xindian'),
    color: 'GREEN',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR24'),
    a: c('tt_xindian'),
    b: c('tt_wulai'),
    color: 'BLUE',
    length: 4,
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR25'),
    a: c('tt_shulin'),
    b: c('tt_banqiao'),
    color: 'GRAY',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.3,
  },
  {
    id: r('TTR26'),
    a: c('tt_yingge'),
    b: c('tt_shulin'),
    color: 'GRAY',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR27'),
    a: c('tt_tucheng'),
    b: c('tt_zhonghe'),
    color: 'GREEN',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: 1.3,
  },
  {
    id: r('TTR28'),
    a: c('tt_banqiao'),
    b: c('tt_tucheng'),
    color: 'BLACK',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.4,
  },
  {
    id: r('TTR29'),
    a: c('tt_sanxia'),
    b: c('tt_tucheng'),
    color: 'BLUE',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR30'),
    a: c('tt_yingge'),
    b: c('tt_sanxia'),
    color: 'GRAY',
    length: 2,
    ferryLocos: 2,
    isTunnel: false,
    bow: 0,
  },
  {
    id: r('TTR31'),
    a: c('tt_tucheng'),
    b: c('tt_shulin'),
    color: 'RED',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.5,
  },
  {
    id: r('TTR32'),
    a: c('tt_cksmemorial'),
    b: c('tt_zhonghe'),
    color: 'WHITE',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.5,
  },
  {
    id: r('TTR33'),
    a: c('tt_xinzhuang'),
    b: c('tt_linkou'),
    color: 'PURPLE',
    length: 4,
    ferryLocos: 0,
    isTunnel: false,
    bow: -1.8,
  },
  {
    id: r('TTR34'),
    a: c('tt_dapinglin'),
    b: c('tt_ankeng'),
    color: 'ORANGE',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: 0.7,
  },
  {
    id: r('TTR35'),
    a: c('tt_luzhou'),
    b: c('tt_shilin'),
    color: 'BLUE',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.1,
  },
  {
    id: r('TTR36'),
    a: c('tt_xinzhuang'),
    b: c('tt_luzhou'),
    color: 'YELLOW',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.8,
  },
  {
    id: r('TTR37'),
    a: c('tt_sanchong'),
    b: c('tt_luzhou'),
    color: 'ORANGE',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
    bow: 0,
  },
  {
    id: r('TTR38'),
    a: c('tt_taipei'),
    b: c('tt_songshan'),
    color: 'GRAY',
    length: 1,
    doubleGroup: 'B',
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR39'),
    a: c('tt_taipei'),
    b: c('tt_songshan'),
    color: 'YELLOW',
    length: 1,
    doubleGroup: 'B',
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR40'),
    a: c('tt_songshan'),
    b: c('tt_nangang'),
    color: 'GRAY',
    length: 1,
    doubleGroup: 'D',
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR41'),
    a: c('tt_songshan'),
    b: c('tt_nangang'),
    color: 'BLUE',
    length: 1,
    doubleGroup: 'D',
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR42'),
    a: c('tt_daan'),
    b: c('tt_songshan'),
    color: 'ORANGE',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR43'),
    a: c('tt_songshan'),
    b: c('tt_neihu'),
    color: 'BLACK',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.6,
  },
  {
    id: r('TTR44'),
    a: c('tt_shulin'),
    b: c('tt_xinzhuang'),
    color: 'GREEN',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.5,
  },
  {
    id: r('TTR45'),
    a: c('tt_sanxia'),
    b: c('tt_wulai'),
    color: 'GRAY',
    length: 6,
    ferryLocos: 0,
    isTunnel: true,
    bow: 2.3,
  },
  {
    id: r('TTR46'),
    a: c('tt_ankeng'),
    b: c('tt_sanxia'),
    color: 'GRAY',
    length: 4,
    ferryLocos: 0,
    isTunnel: true,
    bow: -1.3,
  },
  {
    id: r('TTR47'),
    a: c('tt_tamsui'),
    b: c('tt_bali'),
    color: 'GRAY',
    length: 3,
    ferryLocos: 1,
    isTunnel: false,
    bow: -1.1,
  },
  {
    id: r('TTR48'),
    a: c('tt_nangang'),
    b: c('tt_shiding'),
    color: 'BLACK',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: 0.2,
  },
  {
    id: r('TTR49'),
    a: c('tt_bali'),
    b: c('tt_linkou'),
    color: 'GREEN',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: 2.5,
  },
  {
    id: r('TTR50'),
    a: c('tt_qidu'),
    b: c('tt_anle'),
    color: 'YELLOW',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.3,
  },
  {
    id: r('TTR51'),
    a: c('tt_keelung'),
    b: c('tt_anle'),
    color: 'BLUE',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: 1.8,
  },
  {
    id: r('TTR52'),
    a: c('tt_qidu'),
    b: c('tt_keelung'),
    color: 'GRAY',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: 0,
  },
  {
    id: r('TTR53'),
    a: c('tt_badouzi'),
    b: c('tt_keelung'),
    color: 'GREEN',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR54'),
    a: c('tt_ruifang'),
    b: c('tt_badouzi'),
    color: 'RED',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: 1,
  },
  {
    id: r('TTR55'),
    a: c('tt_pingxi'),
    b: c('tt_nangang'),
    color: 'WHITE',
    length: 4,
    ferryLocos: 0,
    isTunnel: true,
    bow: 0,
  },
  {
    id: r('TTR56'),
    a: c('tt_ruifang'),
    b: c('tt_pingxi'),
    color: 'BLUE',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.6,
  },
  {
    id: r('TTR57'),
    a: c('tt_shuangxi'),
    b: c('tt_ruifang'),
    color: 'BLACK',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: 0.9,
  },
  {
    id: r('TTR58'),
    a: c('tt_fulong'),
    b: c('tt_shuangxi'),
    color: 'RED',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.9,
  },
  {
    id: r('TTR59'),
    a: c('tt_pingxi'),
    b: c('tt_shiding'),
    color: 'RED',
    length: 2,
    ferryLocos: 0,
    isTunnel: true,
    bow: -0.5,
  },
  {
    id: r('TTR60'),
    a: c('tt_shuangxi'),
    b: c('tt_pingxi'),
    color: 'YELLOW',
    length: 3,
    ferryLocos: 0,
    isTunnel: true,
  },
  {
    id: r('TTR61'),
    a: c('tt_fishermanswharf'),
    b: c('tt_danhai'),
    color: 'YELLOW',
    length: 1,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.6,
  },
  {
    id: r('TTR62'),
    a: c('tt_danhai'),
    b: c('tt_tamsui'),
    color: 'ORANGE',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -1.1,
  },
  {
    id: r('TTR63'),
    a: c('tt_fishermanswharf'),
    b: c('tt_bali'),
    color: 'GRAY',
    length: 2,
    ferryLocos: 1,
    isTunnel: false,
    bow: 0.6,
  },
  {
    id: r('TTR64'),
    a: c('tt_fishermanswharf'),
    b: c('tt_tamsui'),
    color: 'WHITE',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: 0,
  },
  {
    id: r('TTR65'),
    a: c('tt_sanzhi'),
    b: c('tt_danhai'),
    color: 'RED',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR66'),
    a: c('tt_shimen'),
    b: c('tt_sanzhi'),
    color: 'BLUE',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: 1,
  },
  {
    id: r('TTR67'),
    a: c('tt_shimen'),
    b: c('tt_jinshan'),
    color: 'GREEN',
    length: 4,
    ferryLocos: 0,
    isTunnel: false,
    bow: -1.6,
  },
  {
    id: r('TTR68'),
    a: c('tt_jinshan'),
    b: c('tt_wanli'),
    color: 'RED',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: 1.5,
  },
  {
    id: r('TTR69'),
    a: c('tt_wanli'),
    b: c('tt_keelung'),
    color: 'ORANGE',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.4,
  },
  {
    id: r('TTR70'),
    a: c('tt_sanzhi'),
    b: c('tt_yangmingshan'),
    color: 'GRAY',
    length: 4,
    ferryLocos: 0,
    isTunnel: false,
    brokenCarriages: 2,
    bow: 2.2,
  },
  {
    id: r('TTR71'),
    a: c('tt_jinshan'),
    b: c('tt_yangmingshan'),
    color: 'GRAY',
    length: 4,
    ferryLocos: 0,
    isTunnel: false,
    brokenCarriages: 2,
    bow: -1.3,
  },
  {
    id: r('TTR72'),
    a: c('tt_shilin'),
    b: c('tt_yangmingshan'),
    color: 'GREEN',
    length: 4,
    ferryLocos: 0,
    isTunnel: false,
    brokenCarriages: 2,
    bow: 1.5,
  },
  {
    id: r('TTR73'),
    a: c('tt_pinglin'),
    b: c('tt_shiding'),
    color: 'WHITE',
    length: 4,
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR74'),
    a: c('tt_pinglin'),
    b: c('tt_xindian'),
    color: 'ORANGE',
    length: 6,
    ferryLocos: 0,
    isTunnel: false,
    bow: -2.1,
  },
  {
    id: r('TTR75'),
    a: c('tt_yangmingshan'),
    b: c('tt_beitou'),
    color: 'YELLOW',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    brokenCarriages: 1,
  },
  {
    id: r('TTR76'),
    a: c('tt_ankeng'),
    b: c('tt_xindian'),
    color: 'BLACK',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.5,
  },
  {
    id: r('TTR77'),
    a: c('tt_shuangxi'),
    b: c('tt_daxi'),
    color: 'WHITE',
    length: 4,
    ferryLocos: 0,
    isTunnel: true,
  },
  {
    id: r('TTR78'),
    a: c('tt_pinglin'),
    b: c('tt_jiaoxi'),
    color: 'GREEN',
    length: 6,
    ferryLocos: 0,
    isTunnel: false,
  },
  {
    id: r('TTR79'),
    a: c('tt_jiaoxi'),
    b: c('tt_shiding'),
    color: 'GRAY',
    length: 8,
    ferryLocos: 0,
    isTunnel: true,
    bow: 2.8,
  },
  {
    id: r('TTR80'),
    a: c('tt_wulai'),
    b: c('tt_jiaoxi'),
    color: 'GRAY',
    length: 6,
    ferryLocos: 0,
    isTunnel: true,
    bow: 0,
  },
  {
    id: r('TTR81'),
    a: c('tt_daxi'),
    b: c('tt_jiaoxi'),
    color: 'GRAY',
    length: 4,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.4,
  },
  {
    id: r('TTR82'),
    a: c('tt_keelung'),
    b: c('tt_keelungislet'),
    color: 'GRAY',
    length: 3,
    ferryLocos: 2,
    isTunnel: false,
    bow: -2.5,
  },
  {
    id: r('TTR83'),
    a: c('tt_badouzi'),
    b: c('tt_keelungislet'),
    color: 'GRAY',
    length: 2,
    doubleGroup: 'E',
    ferryLocos: 2,
    isTunnel: false,
    bow: 0.3,
  },
  {
    id: r('TTR84'),
    a: c('tt_badouzi'),
    b: c('tt_keelungislet'),
    color: 'GRAY',
    length: 2,
    doubleGroup: 'E',
    ferryLocos: 2,
    isTunnel: false,
    bow: 0.3,
  },
  {
    id: r('TTR85'),
    a: c('tt_luzhou'),
    b: c('tt_bali'),
    color: 'BLACK',
    length: 4,
    ferryLocos: 0,
    isTunnel: false,
    bow: -1.3,
  },
  {
    id: r('TTR86'),
    a: c('tt_shiding'),
    b: c('tt_muzha'),
    color: 'ORANGE',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.5,
  },
  {
    id: r('TTR87'),
    a: c('tt_fulong'),
    b: c('tt_daxi'),
    color: 'BLUE',
    length: 3,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.9,
  },
  {
    id: r('TTR88'),
    a: c('tt_linkou'),
    b: c('tt_taoyuan'),
    color: 'BLACK',
    length: 4,
    ferryLocos: 0,
    isTunnel: false,
    bow: 2,
  },
  {
    id: r('TTR89'),
    a: c('tt_xinzhuang'),
    b: c('tt_taoyuan'),
    color: 'ORANGE',
    length: 6,
    ferryLocos: 0,
    isTunnel: false,
    bow: -0.6,
  },
  {
    id: r('TTR90'),
    a: c('tt_yingge'),
    b: c('tt_taoyuan'),
    color: 'GRAY',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -1.1,
  },
  {
    id: r('TTR91'),
    a: c('tt_songshan'),
    b: c('tt_muzha'),
    color: 'RED',
    length: 2,
    ferryLocos: 0,
    isTunnel: false,
    bow: -1,
  },
];
